#+title: Final Assignment's Labbook
#+author: Henrique Silva
#+email: hcpsilva@inf.ufrgs.br
#+infojs_opt:
#+property: session *R*
#+property: cache yes
#+property: results graphics
#+property: exports both
#+property: tangle yes

Welcome to this project's lab-book! Here I'll organize my thoughts and perhaps
put my scripts and so on and so forth.

As you may know, in this assignment we're expected to implement one or more
modules of a processor that's being simulated:

- *Prefetcher*
- *Cache substitution policy*
- *Branch predictor*

As of now we are still considering the options as of which of those we should
implement.

* Journal

Thoughts and stuff.

** 2019-12-25

Merry Christmas I guess. So, we've got a preliminary list of what applications
to test, which is always useful, but still no idea of which element to
implement. Here's an excerpt:

#+begin_quote
- bzip2 :: integer. Imagino que compressão tenha um padrão de acesso aos dados
           contíguo e regular. Desse modo, com um prefetcher stream a gente
           consegue tirar mais proveito do que com um prefetcher strided por
           ex. Ainda mostraria como qualquer algoritmo de substituição não seria
           lá muito eficiente. Checar com Francis.
- gcc :: Acessos bem irregulares pros quais é difícil acertar qualquer
         coisa. Also é importante lembrar que haverá melhoras de uma
         configuração pra outra por conta da evolução dos branch predictors
         escolhidos.
- astar :: integer. Algoritmos de path finding em ambiente 2D.
- povray :: ray tracing. Normalmente OO, o que torna o acesso à mem
            interessante.  Also: iterações pelos objetos a cada pulo, teste de
            intersecção: branch predictor.
- calculix :: matrizes esparsas pra resolver equações diferenciais. Matrizes
              esparsas.
#+end_quote

I mean, I've got no idea of what benchmarks exercise the different parts of the
processor, so I'm all for it. As far as the simulator goes, I'll try to figure
out how it works. Time to read that convoluted =readme=...

So, I've understood how it works (because it's really easy to build and run
stuff). Thing is, I have absolutely no idea on how to implement the stuff
mentioned previously (the new policies, etc). Like, really no idea. I took a
look at all the modules we could implement, but they're really not that easy to
understand, which may have something to do with the fact that I don't know this
architecture stuff in the first place. And I'm kinda traumatized to go search in
those terrible slides because of my previous experiences.

I doubt that this simulator has seen some use in the academy, but I'll go look
for something anyways...

Well, I'll be damned! Here are some links:

- [[https://arxiv.org/pdf/1906.00877.pdf]]
- [[http://nope.pub/papers/2017/gomes2017watermarking.pdf]]
- [[https://www.usenix.org/system/files/woot19-paper_kumar.pdf]]

There are more, but the point was made. I think those are a bit overkill for a
simple uni assignment, because all of them verse about some really
state-of-the-art stuff. I'm thinking about finding some novel approach proposed
in the 80s-90s and implementing it, as these ought to be significantly simpler
than the ones I've collected.

Besides that stuff, I'm looking forward into having access to the report so I
can use the IEEE template.
